/*
 *
 *  Copyright 2018-2019 the original author or authors.
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *         http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 *
 *
 */
package springfox.javadoc.plugin;

import org.springframework.core.env.Environment;
import springfox.documentation.service.ResolvedMethodParameter;
import springfox.documentation.spi.DocumentationType;
import springfox.documentation.spi.service.ParameterBuilderPlugin;
import springfox.documentation.spi.service.contexts.ParameterContext;
import springfox.javadoc.doclet.SwaggerPropertiesDoclet;

import java.lang.annotation.Annotation;
import java.lang.reflect.Method;
import java.util.Optional;

import static springfox.javadoc.plugin.AnnotationHelper.hasValue;

/**
 * Plugin to generate the @ApiParam and @ApiOperation values from the properties
 * file generated by the {@link SwaggerPropertiesDoclet}.
 *
 * @author rgoers
 * @author MartinNeumannBeTSE
 */
public class JavadocParameterBuilderPlugin implements ParameterBuilderPlugin {

    private static final String PERIOD = ".";
    private static final String API_PARAM = "io.swagger.annotations.ApiParam";
    private static final String REQUEST_PARAM = "org.springframework.web.bind.annotation.RequestParam";
    private static final String PATH_VARIABLE = "org.springframework.web.bind.annotation.PathVariable";
    private final Environment environment;

    public JavadocParameterBuilderPlugin(Environment environment) {
        this.environment = environment;
    }

    private static Annotation annotationFromField(ParameterContext context, String annotationType) {

        ResolvedMethodParameter methodParam = context.resolvedMethodParameter();

        for (Annotation annotation : methodParam.getAnnotations()) {
            if (annotation.annotationType().getName().equals(annotationType)) {
                return annotation;
            }
        }
        return null;

    }

    @Override
    public boolean supports(DocumentationType delimiter) {
        return true;
    }

    @Override
    public void apply(ParameterContext context) {
        String description = null;
        Optional<String> parameterName = context.resolvedMethodParameter().defaultName();
        Annotation apiParam = annotationFromField(context, API_PARAM);
        if (apiParam != null) {
            java.util.Optional<Boolean> isRequired = isParamRequired(apiParam, context);
            isRequired.ifPresent(aBoolean -> context.parameterBuilder().required(aBoolean));
        }
        if (parameterName.isPresent() && (apiParam == null || !hasValue(apiParam))) {
            String key = context.getOperationContext().requestMappingPattern() + PERIOD
              + context.getOperationContext().httpMethod().name() + ".param." + parameterName.get();
            description = environment.getProperty(key);
        }
        if (description != null) {
            context.parameterBuilder().description(description);
        }
    }

    private java.util.Optional<Boolean> isParamRequired(Annotation apiParam, ParameterContext context) {
        if (apiParam != null) {
            java.util.Optional<Boolean> required = isRequired(apiParam);
            if (required.isPresent()) {
                return required;
            }
        }
        Annotation annotation = annotationFromField(context, REQUEST_PARAM);
        if (annotation == null) {
            annotation = annotationFromField(context, PATH_VARIABLE);
        }
        return annotation != null ? isRequired(annotation) : java.util.Optional.empty();
    }

    private java.util.Optional<Boolean> isRequired(Annotation annotation) {
        for (Method method : annotation.annotationType().getDeclaredMethods()) {
            if (method.getName().equals("required")) {
                try {
                    return java.util.Optional.of((Boolean) method.invoke(annotation, (Object) null));
                } catch (Exception ex) {
                    return java.util.Optional.empty();
                }
            }
        }
        return java.util.Optional.empty();
    }

}
